### ISSUE TITLE
Convention of restful routes

### ISSUE THREAD

**Issue by TayKangSheng** [wdi-sg/wdi-project-2-jonathanlimes#1]
Referring to issues_router.js

Learn to use the correct HTTP verbs (GET, POST, PUT, DELETE etc..) for different actions that the user wants to do. Although the usage of these verbs are by convention and is not a must to use them correctly in order to achieve your intent. But they are there to help you segregate the kind of actions user wants to do. 

One example would be the route that fixes the particular issue. "/:id/fix" is called to update the isFixed parameter in the database. Then you should use PUT instead of GET. The intent of GET is to get a particular information. The intent of PUT is to update information. 

GET -> Get information
POST -> Create information
PUT -> Update information
Delete -> Delete information

**Comment by jonathanlimes** [comment]
Noted! "/:id/fix" has been changed to a PUT request as follows:

issue_router.js -
```
router.put('/:id/fix', isNotLoggedIn, issueController.fix)
```

in my ejs view -
```
      <form method="POST" action="/issues/<%=issue.id%>/fix?_method=PUT&isFixed=true">
          <button class="btn btn-success" type="submit">
            <span class="glyphicon glyphicon-ok-circle"></span> Fix Issue
          </button>
      </form>
```
