### ISSUE TITLE
Signup with for city admin

### ISSUE THREAD

**Issue by primaulia** [wdi-sg/wdi-project-2-jonathanlimes#4]
triggers application error

**Comment by jonathanlimes** [comment]
Heroku app has been redeployed, error rectified. You now have admin access.

I will be adding authentication for admin registration by tomorrow (upon a correct 'admin ID', allow creation of a user instance with `isAdmin = true`)

**Comment by jonathanlimes** [comment]
Authentication for admin has been added!
